# Runs when PR is created, updated, or reopened

name: Deploy to Firebase Hosting on PR
on: pull_request
jobs:
  build_and_preview:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23.11.0"
      - name: Check node.js version
        run: node -v
      - name: Install pnpm
        run: npm install -g pnpm@10.8.0
      - name: Check pnpm version
        run: pnpm -v
      - name: Install dependencies
        run: pnpm install
      - name: Check dependencies version
        run: |
          pnpm view @astrojs/check version
          pnpm view astro version
          pnpm view firebase-tools version
          pnpm view hotkeypad version
          pnpm view typescript version
      - name: Build
        run: pnpm build
      - name: Enable Firebase experiments
        run: pnpm exec firebase experiments:enable webframeworks
      - name: Firebase Deploy Preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_HIMANSHUJAIN_DEV }}"
          projectId: himanshujain-dev
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
      - name: Send status message
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COMMENT="Congratulations! The build was successful."
          curl -sSL -H "Authorization: token $GITHUB_TOKEN" -d "{\"body\": \"$COMMENT\"}" -H "Content-Type: application/json" -X POST "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${{ github.event.pull_request.number }}/comments"
      - name: Send failure message with error details
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COMMENT="Oops! The build failed."
          curl -sSL -H "Authorization: token $GITHUB_TOKEN" -d "{\"body\": \"$COMMENT\"}" -H "Content-Type: application/json" -X POST "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${{ github.event.pull_request.number }}/comments"
